// <auto-generated />
using System;
using MYT.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MYT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200203124247_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MYT.Data.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("MYT.Data.Entity.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Priority");
                });

            modelBuilder.Entity("MYT.Data.Entity.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDone");

                    b.Property<DateTime>("LastChanged");

                    b.Property<int?>("ListId");

                    b.Property<int>("PriorityID");

                    b.Property<string>("Theme");

                    b.Property<DateTime>("TimeOfCreate");

                    b.Property<int?>("UserIdId");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("PriorityID");

                    b.HasIndex("UserIdId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("MYT.Data.Entity.TodoItemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDone");

                    b.Property<DateTime>("LastChanged");

                    b.Property<int>("PriorityId");

                    b.Property<string>("Theme");

                    b.Property<DateTime>("TimeOfCreate");

                    b.Property<int?>("UserIdId");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("UserIdId");

                    b.ToTable("TodoItemLists");
                });

            modelBuilder.Entity("MYT.Data.Entity.TodoItem", b =>
                {
                    b.HasOne("MYT.Data.Entity.TodoItemList", "TodoItemList")
                        .WithMany("TodoItems")
                        .HasForeignKey("ListId");

                    b.HasOne("MYT.Data.Entity.Priority", "Priority")
                        .WithMany("TodoItems")
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MYT.Data.Entity.ApplicationUser", "UserId")
                        .WithMany()
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("MYT.Data.Entity.TodoItemList", b =>
                {
                    b.HasOne("MYT.Data.Entity.Priority", "Priority")
                        .WithMany("TodoItemLists")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MYT.Data.Entity.ApplicationUser", "UserId")
                        .WithMany()
                        .HasForeignKey("UserIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
